import{a as d,i as p}from"./assets/vendor-96017409.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();d.defaults.headers.common["x-api-key"]="live_NXtFYyIyi6WXrDnJSG1ixW6MQi3wZYfksHpLsoKbmmCpFoezfA46Kb4dRh3yr5Yq";async function m(){return(await d.get("https://api.thecatapi.com/v1/breeds")).data}async function f(e){return(await d.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`)).data}const u=document.querySelector("body"),a=document.querySelector(".select"),c=document.querySelector(".loader"),l=document.querySelector(".cat-info");a.style.display="none";document.addEventListener("DOMContentLoaded",g);a.addEventListener("change",y);async function y(e){const n=e.target.value;try{l.style.display="none",c.style.display="block";const r=await f(n);c.style.display="none",b(r)}catch(r){u.innerHTML="Ooops, something went wrong!...Try again later",p.error({message:"Failed to load content",position:"topRight",backgroundColor:"red",messageColor:"rgb(231, 231, 219)",iconColor:"rgb(231, 231, 219)"}),console.log(`${r.message}`)}}async function g(){try{const e=await m();console.log(e),c.style.display="none",h(e),a.style.display="flex"}catch(e){u.innerHTML="Ooops, something went wrong!...Try again later",p.error({message:"Failed to load content",position:"topRight"}),console.log(`${e.message}`)}}function h(e){const n=e.map(({id:r,name:s})=>`<option value="${r}">${s}</option>`).join("");a.innerHTML=`<select class="breed-select" id="selectElement">${n}</select>`}function b(e){l.style.display="flex";const n=`<img class="cat-img" src="${e[0].url}" alt="${e[0].breeds[0].name}"  />
    <div class="breed-info">
      <h1 class="cat-name">${e[0].breeds[0].name}</h1>
      <p class="description">${e[0].breeds[0].description}</p>
      <h2 class="temperament">Temperament:</h2>
      <p class="temp-descr">${e[0].breeds[0].temperament}</p>
    </div>
    `;return l.innerHTML=n}
//# sourceMappingURL=commonHelpers.js.map
